export const searchByName = (searchTerm, list) => {
  const searchLower = searchTerm.toLowerCase();
  const filteredList = list.filter(
    (patient) =>
      patient.koreanName.toLowerCase().includes(searchLower) ||
      patient.englishName.toLowerCase().includes(searchLower)
  );
  return filteredList;
};

export const patientList = [
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 30,
    sagittalNeckLowerAngle: 40,
    frontalNeckLeftAngle: 20,
    frontalNeckRightAngle: 20,
    horizontalLeftArmUpperAngle: 25,
    horizontalLeftArmLowerAngle: 25,
    horizontalRightArmUpperAngle: 30,
    horizontalRightArmLowerAngle: 30,
    sagittalLeftArmFrontAngle: 15,
    sagittalLeftArmRearAngle: 15,
    sagittalRightArmFrontAngle: 22,
    sagittalRightArmRearAngle: 22,
    frontalLeftArmOuterAngle: 14,
    frontalLeftArmInnerAngle: 14,
    frontalRightArmOuterAngle: 20,
    frontalRightArmInnerAngle: 20,
    sagittalWaistRearAngle: 15,
    sagittalWaistFrontAngle: 15,
    frontalWaistLeftAngle: 16,
    frontalWaistRightAngle: 21,
    leftKneeRearAngle: 21,
    rightKneeRearAngle: 30,
    headTwisted: 30,
    shoulderTwisted: 26,
    pelvisTwisted: 26,
    neckTwisted: 18,
    shoulderRolled: 18,
    createdAt: "2024-06-14"
  },
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 45,
    sagittalNeckLowerAngle: 34,
    frontalNeckLeftAngle: 23,
    frontalNeckRightAngle: 54,
    horizontalLeftArmUpperAngle: 37,
    horizontalLeftArmLowerAngle: 29,
    horizontalRightArmUpperAngle: 46,
    horizontalRightArmLowerAngle: 52,
    sagittalLeftArmFrontAngle: 32,
    sagittalLeftArmRearAngle: 58,
    sagittalRightArmFrontAngle: 44,
    sagittalRightArmRearAngle: 38,
    frontalLeftArmOuterAngle: 47,
    frontalLeftArmInnerAngle: 50,
    frontalRightArmOuterAngle: 30,
    frontalRightArmInnerAngle: 33,
    sagittalWaistRearAngle: 59,
    sagittalWaistFrontAngle: 49,
    frontalWaistLeftAngle: 31,
    frontalWaistRightAngle: 37,
    leftKneeRearAngle: 44,
    rightKneeRearAngle: 57,
    headTwisted: 51,
    shoulderTwisted: 35,
    pelvisTwisted: 60,
    neckTwisted: 33,
    shoulderRolled: 28,
    createdAt: "2024-06-15"
  },
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 34,
    sagittalNeckLowerAngle: 42,
    frontalNeckLeftAngle: 28,
    frontalNeckRightAngle: 37,
    horizontalLeftArmUpperAngle: 29,
    horizontalLeftArmLowerAngle: 53,
    horizontalRightArmUpperAngle: 31,
    horizontalRightArmLowerAngle: 44,
    sagittalLeftArmFrontAngle: 57,
    sagittalLeftArmRearAngle: 50,
    sagittalRightArmFrontAngle: 54,
    sagittalRightArmRearAngle: 39,
    frontalLeftArmOuterAngle: 46,
    frontalLeftArmInnerAngle: 40,
    frontalRightArmOuterAngle: 30,
    frontalRightArmInnerAngle: 34,
    sagittalWaistRearAngle: 60,
    sagittalWaistFrontAngle: 58,
    frontalWaistLeftAngle: 53,
    frontalWaistRightAngle: 42,
    leftKneeRearAngle: 33,
    rightKneeRearAngle: 40,
    headTwisted: 46,
    shoulderTwisted: 50,
    pelvisTwisted: 58,
    neckTwisted: 43,
    shoulderRolled: 31,
    createdAt: "2024-06-16"
  },
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 35,
    sagittalNeckLowerAngle: 54,
    frontalNeckLeftAngle: 32,
    frontalNeckRightAngle: 37,
    horizontalLeftArmUpperAngle: 49,
    horizontalLeftArmLowerAngle: 31,
    horizontalRightArmUpperAngle: 42,
    horizontalRightArmLowerAngle: 38,
    sagittalLeftArmFrontAngle: 48,
    sagittalLeftArmRearAngle: 30,
    sagittalRightArmFrontAngle: 39,
    sagittalRightArmRearAngle: 51,
    frontalLeftArmOuterAngle: 60,
    frontalLeftArmInnerAngle: 33,
    frontalRightArmOuterAngle: 45,
    frontalRightArmInnerAngle: 49,
    sagittalWaistRearAngle: 55,
    sagittalWaistFrontAngle: 44,
    frontalWaistLeftAngle: 34,
    frontalWaistRightAngle: 35,
    leftKneeRearAngle: 50,
    rightKneeRearAngle: 32,
    headTwisted: 39,
    shoulderTwisted: 60,
    pelvisTwisted: 47,
    neckTwisted: 37,
    shoulderRolled: 33,
    createdAt: "2024-06-17"
  },
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 43,
    sagittalNeckLowerAngle: 51,
    frontalNeckLeftAngle: 45,
    frontalNeckRightAngle: 53,
    horizontalLeftArmUpperAngle: 60,
    horizontalLeftArmLowerAngle: 37,
    horizontalRightArmUpperAngle: 35,
    horizontalRightArmLowerAngle: 49,
    sagittalLeftArmFrontAngle: 48,
    sagittalLeftArmRearAngle: 57,
    sagittalRightArmFrontAngle: 31,
    sagittalRightArmRearAngle: 47,
    frontalLeftArmOuterAngle: 56,
    frontalLeftArmInnerAngle: 33,
    frontalRightArmOuterAngle: 42,
    frontalRightArmInnerAngle: 40,
    sagittalWaistRearAngle: 46,
    sagittalWaistFrontAngle: 55,
    frontalWaistLeftAngle: 43,
    frontalWaistRightAngle: 44,
    leftKneeRearAngle: 52,
    rightKneeRearAngle: 38,
    headTwisted: 31,
    shoulderTwisted: 58,
    pelvisTwisted: 33,
    neckTwisted: 50,
    shoulderRolled: 39,
    createdAt: "2024-06-18"
  },
  {
    birthDate: "1980.12.01",
    koreanName: "홍길동",
    englishName: "HongRoadDong",
    gender: "남성",
    sagittalNeckUpperAngle: 50,
    sagittalNeckLowerAngle: 39,
    frontalNeckLeftAngle: 47,
    frontalNeckRightAngle: 43,
    horizontalLeftArmUpperAngle: 35,
    horizontalLeftArmLowerAngle: 58,
    horizontalRightArmUpperAngle: 38,
    horizontalRightArmLowerAngle: 41,
    sagittalLeftArmFrontAngle: 39,
    sagittalLeftArmRearAngle: 49,
    sagittalRightArmFrontAngle: 44,
    sagittalRightArmRearAngle: 50,
    frontalLeftArmOuterAngle: 53,
    frontalLeftArmInnerAngle: 51,
    frontalRightArmOuterAngle: 48,
    frontalRightArmInnerAngle: 40,
    sagittalWaistRearAngle: 57,
    sagittalWaistFrontAngle: 33,
    frontalWaistLeftAngle: 36,
    frontalWaistRightAngle: 46,
    leftKneeRearAngle: 31,
    rightKneeRearAngle: 60,
    headTwisted: 38,
    shoulderTwisted: 36,
    pelvisTwisted: 32,
    neckTwisted: 45,
    shoulderRolled: 60,
    createdAt: "2024-06-19"
  }
];